### ISSUE TITLE
Slow package installation. 

### ISSUE THREAD

**Issue by eash-veera** [luangjokaj/gopablo#3]
Tried it with different connection speeds, averaging between 25 - 56 mbps , yet package takes a long time to install via npm, or is it just me ?

**Comment by luangjokaj** [comment]
I just pushed an improvement for the installation speed of the first-time global dependency (b2bb241c29ff62d05f469cbe506d217472a58fa3). However, setting up a new static site will take a bit longer as it requires more dependencies to compile all the assets of the website. 

I recommend you to do a `sudo npm install gopablo -g` as version 0.0.9 is out and `package.json` has changed thus it's a **breaking change**.
