### ISSUE TITLE
cherry-postcss error

### ISSUE THREAD

**Issue by mosafer72** [luangjokaj/gopablo#8]
hi
I am trying to install gopablo with "npx gopablo"

but get this error

npm error code ENOVERSIONS
npm error No versions available for cherry-postcss

**Comment by luangjokaj** [comment]
> hi I am trying to install gopablo with "npx gopablo"
> 
> but get this error
> 
> npm error code ENOVERSIONS npm error No versions available for cherry-postcss

I just pushed v0.1.5-8 to fix this issue. The cherry-postcss is deprecated, to fix your version just remove the package:
`npm remove cherry-postcss` or use the latest GoPablo v0.1.5-8.
